spring.application.name=buildlogai

spring.profiles.active=dev

spring.config.import=optional:file:.env[.properties]

openai.api.key=${OPENAI_API_KEY}
google.gemini.api.key=${GOOGLE_GEMINI_API_KEY}
google.gemini.project.id=${GOOGLE_GEMINI_PROJECT_ID}
google.gemini.location=${GOOGLE_GEMINI_LOCATION}

server.address=0.0.0.0
server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

